# Todo: 要改成真正的库名和密码
services:
  mysql:
    image: mysql:8.0
    container_name: go-ai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_task
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Shanghai
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+08:00
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script/mysql/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    container_name: go-ai-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# 声明使用了两个挂载卷
volumes:
  mysql_data:
  redis_data: